# Compose ファイルの書式のバージョン
# version: "3.8"
 
# docker-composeではserviceという単位でコンテナを管理する
services:
  php:
    # コンテナ名
    container_name: php
    # phpのイメージをbuildするためのDockerfileへのパス
    build:
    # contextでフォルダを指定することでフォルダ内のファイルとDockerfileを使って、イメージを作る
      context: ./php
    # ホストの「ポート番号」 8080 とコンテナの「ポート番号」 80 を対応付け
    ports:
      - 8080:80
    # ホストのsrcディレクトリをコンテナ内の/var/www/htmlというディレクトリにマウント
    volumes:
      - ./src:/var/www/html
      - ./vendor:/var/www/vendor
      - ./setting:/var/www/setting
    # dockerの再起動などの際にコンテナも再起動させる
    restart: always
    # コンテナにドメイン名を割り当てる
    # networks:
    #   default:
    #     aliases:
    #       - main.site

  db:
    container_name: mysql
    # "mysql:8.0.23"のイメージを使用
    image: mysql:8.0.23
    volumes:
      - ./db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
    # コンテナ内で利用する環境変数を設定
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: init_db
    # コンテナ生成後にコンテナ内で実行するコマンド
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.1.3
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    # 他のコンテナと通信（指定したコンテナの情報が取得可能）
    links:
      - db
    ports:
      - 8081:80
    volumes:
      - ./php/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
      - ./php/Core.php:/var/www/html/libraries/classes/Core.php

  mailpit:
    container_name: mail
    image: axllent/mailpit:v1.20
    ports: 
      - 8025:8025
      - 1025:1025
    volumes:
      - ./mailpit:/data
    environment:
      TZ: Asia/Tokyo
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

# ホストOS(PC)上にボリュームを定義
# これでdb_dataという名前のデータ保存領域がホストOS(PC)上に作成される
volumes:
  db_data:
